[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.ruff]
# Igual que flake8: errores, warnings, etc.
line-length = 88
select = ["E", "F", "W", "C90", "RUF"]
ignore = ["E203"]

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true
strict = false
